#pragma once

enum errorType {
	UNDEF_ID = 1, MULTI_DEF, IDENT_TOO_LONG, PROGRAM_ERROR, STR_CONTENT_ERROR, STR_MISSINT_RPARENT, ZERO_HEAD_NUM,
	NUM_HEAD_IDENT, NUM_TOO_LARGE, UNDEF_INPUT, CHAR_MISS_QUOTE, CHAR_CONTENT_ERROR, NEQUAL_MISS, 
	MISSING_SEMICOLON, MISSING_RPARENT, MISSING_RBRACK, MISSING_RBRACE, MISSING_IDENT, ERROR_PARA_NUM, 
	MISSING_LPARENT, MISSING_LBRACK, MISSING_LBRACE, MISSING_PLUS, MISSING_MULTI, MISSING_IS, RETURN_ERROR,
	MISSING_MAIN, MISSING_RETURN, EXPRESSION_ERROR, CONST_NOT_INIT, VAR_NOT_INIT, FUNC_NO_RET, OUT_OF_TABLE, 
	OUT_OF_ARRAY, WRONG_TYPE, FILE_NOT_EXIST, ILLEGAL_WORD, STR_EMPTY, MISSING_INTEGER, MISSING_CHAR, MISSING_NUMBER, 
	FACTOR_CONTENT_WRONG, MISSING_CASE_KEYWORD, CASE_CONTENT_WRONG, MISSING_COLON, SENTENCE_CONTENT_WRONG, 
	FUNC_NO_DEFINED, WRONG_ASSIGN_TYPE
};

void error(enum errorType errorNum);

int errorflag;