#pragma once

enum errorType {
	UNDEF_ID = 1, MULTI_DEF, PROGRAM_ERROR, STR_EMPTY, STR_CONTENT_ERROR, STR_MISSINT_RPARENT, 
	ZERO_HEAD_NUM, CHAR_MISS_QUOTE, CHAR_CONTENT_ERROR, NEQUAL_MISS, MISSING_SEMICOLON, MISSING_COLON, 
	MISSING_RPARENT, MISSING_RBRACK, MISSING_RBRACE, MISSING_IDENT, ERROR_PARA_NUM, MISSING_LPARENT, 
	MISSING_LBRACE, MISSING_INTEGER, MISSING_NUMBER, MISSING_IS, MISSING_CHAR, RETURN_ERROR, 
	MISSING_MAIN, MISSING_CASE_KEYWORD, WRONG_ASSIGN_TYPE, CASE_CONTENT_WRONG, FACTOR_CONTENT_WRONG,
	SENTENCE_CONTENT_WRONG, OUT_OF_ARRAY, WRONG_TYPE, FILE_NOT_EXIST, ILLEGAL_WORD, FUNC_NO_DEFINED, 
	FUNC_NO_RET, ERROR_PARA_TYPE, ASSIG2CONST, CONDITION_TYPE_ERROR, ARRAY_INDEX_NOT_INT, 
	SWITCH_TYPE_ERROR
};

void error(enum errorType errorNum);

int errorflag;